using System;
using System.Collections.Generic;
using System.Data.Entity;
using WebApiMovieRest.Core.Domain;

namespace WebApiMovieRest.Core.Persistence
{
    public class WebApiMovieRestInitializer : DropCreateDatabaseIfModelChanges<WebApiMovieRestContext>
    {
        protected override void Seed(WebApiMovieRestContext context)
        {
            SeedMovies().ForEach(movie => context.Movies.Add(movie));

            base.Seed(context);
        }

        public List<Movie> SeedMovies()
        {
            var action = new Genre("Action");
            var adventure = new Genre("Adventure");
            var animation = new Genre("Animation");
            var biography = new Genre("Biography");
            var comedy = new Genre("Comedy");
            var crime = new Genre("Crime");
            var drama = new Genre("Drama");
            var family = new Genre("Family");
            var fantasy = new Genre("Fantasy");
            var filmNoir = new Genre("Film-Noir");
            var history = new Genre("History");
            var horror = new Genre("Horror");
            var music = new Genre("Music");
            var musical = new Genre("Musical");
            var mystery = new Genre("Mystery");
            var romance = new Genre("Romance");
            var sciFi = new Genre("Sci-Fi");
            var thriller = new Genre("Thriller");
            var war = new Genre("War");
            var western = new Genre("Western");

            var movies = new List<Movie>
            {
                new Movie("tt0111161", "The Shawshank Redemption", 9.3m, "Frank Darabont", new DateTime(1994,10,14), "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", new[] { crime, drama }), 
                new Movie("tt0068646", "The Godfather", 9.2m, "Francis Ford Coppola", new DateTime(1972,03,24), "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", new[] { crime, drama }), 
                new Movie("tt0071562", "The Godfather: Part II", 9m, "Francis Ford Coppola", new DateTime(1974,12,20), "The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.", new[] { crime, drama }), 
                new Movie("tt0110912", "Pulp Fiction", 9m, "Quentin Tarantino", new DateTime(1994,10,14), "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", new[] { crime, drama, thriller }), 
                new Movie("tt0468569", "The Dark Knight", 9m, "Christopher Nolan", new DateTime(2008,07,18), "When Batman, Gordon and Harvey Dent launch an assault on the mob, they let the clown out of the box, the Joker, bent on turning Gotham on itself and bringing any heroes down to his level.", new[] { action, crime, drama, thriller }), 
                new Movie("tt0050083", "12 Angry Men", 8.9m, "Sidney Lumet", new DateTime(1957,04,01), "A dissenting juror in a murder trial slowly manages to convince the others that the case is not as obviously clear as it seemed in court.", new[] { drama }), 
                new Movie("tt0108052", "Schindler's List", 8.9m, "Steven Spielberg", new DateTime(1993,12,15), "In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.", new[] { biography, drama, history, war }), 
                new Movie("tt0167260", "The Lord of the Rings: The Return of the King", 8.9m, "Peter Jackson", new DateTime(2004,03,12), "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", new[] { action, adventure, fantasy }), 
                new Movie("tt0137523", "Fight Club", 8.9m, "David Fincher", new DateTime(1999,10,15), "An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...", new[] { drama }), 
                new Movie("tt0080684", "Star Wars: Episode V - The Empire Strikes Back", 8.8m, "Irvin Kershner", new DateTime(1980,05,21), "After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.", new[] { action, adventure, sciFi }), 
                new Movie("tt0120737", "The Lord of the Rings: The Fellowship of the Ring", 8.8m, "Peter Jackson", new DateTime(2001,12,19), "A meek hobbit of The Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.", new[] { action, adventure, fantasy }), 
                new Movie("tt0073486", "One Flew Over the Cuckoo's Nest", 8.8m, "Milos Forman", new DateTime(1975,11,21), "Upon admittance to a mental institution, a brash rebel rallies the patients to take on the oppressive head nurse, a woman he views as more dictator than nurse.", new[] { drama }), 
                new Movie("tt1375666", "Inception", 8.8m, "Christopher Nolan", new DateTime(2010,09,01), "A skilled extractor is offered a chance to regain his old life as payment for a task considered to be impossible.", new[] { action, adventure, mystery, sciFi, thriller }), 
                new Movie("tt0099685", "Goodfellas", 8.8m, "Martin Scorsese", new DateTime(1990,09,19), "Henry Hill and his friends work their way up through the mob hierarchy.", new[] { biography, crime, drama, thriller }), 
                new Movie("tt0076759", "Star Wars", 8.8m, "George Lucas", new DateTime(1977,05,25), "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the universe from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.", new[] { action, adventure, fantasy, sciFi }), 
                new Movie("tt0109830", "Forrest Gump", 8.7m, "Robert Zemeckis", new DateTime(1994,07,06), "Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.", new[] { drama, romance }), 
                new Movie("tt0133093", "The Matrix", 8.7m, "Andy Wachowski", new DateTime(1999,03,31), "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", new[] { action, adventure, sciFi }), 
                new Movie("tt0167261", "The Lord of the Rings: The Two Towers", 8.7m, "Peter Jackson", new DateTime(2003,04,26), "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", new[] { action, adventure, fantasy }), 
                new Movie("tt0114369", "Se7en", 8.7m, "David Fincher", new DateTime(1995,09,22), "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.", new[] { crime, mystery, thriller }), 
                new Movie("tt0102926", "The Silence of the Lambs", 8.7m, "Jonathan Demme", new DateTime(1991,02,14), "A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.", new[] { crime, drama, thriller }), 
                new Movie("tt0034583", "Casablanca", 8.7m, "Michael Curtiz", new DateTime(1943,07,07), "Set in unoccupied Africa during the early days of World War II: An American expatriate meets a former lover, with unforeseen complications.", new[] { drama, romance, war }), 
                new Movie("tt0114814", "The Usual Suspects", 8.7m, "Bryan Singer", new DateTime(1995,08,16), "A boat has been destroyed, criminals are dead, and the key to this mystery lies with the only survivor and his twisted, convoluted story beginning with five career crooks in a seemingly random police lineup.", new[] { crime, mystery, thriller }), 
                new Movie("tt0082971", "Raiders of the Lost Ark", 8.6m, "Steven Spielberg", new DateTime(1987,12,11), "Archeologist and adventurer Indiana Jones is hired by the US government to find the Ark of the Covenant before the Nazis.", new[] { action, adventure }), 
                new Movie("tt0047396", "Rear Window", 8.6m, "Alfred Hitchcock", new DateTime(1955,01,29), "A wheelchair bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.", new[] { mystery, thriller }), 
                new Movie("tt0038650", "It's a Wonderful Life", 8.7m, "Frank Capra", new DateTime(1947,01,07), "An angel helps a compassionate but despairingly frustrated businessman by showing what life would have been like if he never existed.", new[] { drama, family, fantasy }), 
                new Movie("tt0054215", "Psycho", 8.6m, "Alfred Hitchcock", new DateTime(1960,09,08), "A Phoenix secretary steals $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.", new[] { horror, mystery, thriller }), 
                new Movie("tt0043014", "Sunset Blvd.", 8.6m, "Billy Wilder", new DateTime(1950,08,25), "A hack screenwriter writes a screenplay for a former silent-film star who has faded into Hollywood obscurity.", new[] { drama, filmNoir }), 
                new Movie("tt0120586", "American History X", 8.6m, "Tony Kaye", new DateTime(1999,02,12), "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.", new[] { crime, drama }), 
                new Movie("tt0078788", "Apocalypse Now", 8.6m, "Francis Ford Coppola", new DateTime(1979,08,15), "During the U.S.-Viet Nam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade colonel who has set himself up as a god among a local tribe.", new[] { drama, war }), 
                new Movie("tt0103064", "Terminator 2: Judgment Day", 8.6m, "James Cameron", new DateTime(1991,07,03), "The cyborg who once tried to kill Sarah Connor is dead, and another T-101 must now protect her teenage son, John Connor, from an even more powerful and advanced Terminator, the T-1000.", new[] { action, sciFi, thriller }), 
                new Movie("tt0209144", "Memento", 8.6m, "Christopher Nolan", new DateTime(2000,10,11), "A man, suffering from short-term memory loss, uses notes and tattoos to hunt for the man he thinks killed his wife.", new[] { mystery, thriller }), 
                new Movie("tt0120815", "Saving Private Ryan", 8.6m, "Steven Spielberg", new DateTime(1998,07,24), "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", new[] { action, drama, war }), 
                new Movie("tt0021749", "City Lights", 8.6m, "Charles Chaplin", new DateTime(1931,03,07), "The Tramp struggles to help a blind flower girl he has fallen in love with.", new[] { comedy, drama, romance }), 
                new Movie("tt0057012", "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", 8.6m, "Stanley Kubrick", new DateTime(1964,01,29), "An insane general starts a process to nuclear holocaust that a war room of politicians and generals frantically try to stop.", new[] { comedy, sciFi, war }), 
                new Movie("tt0078748", "Alien", 8.5m, "Ridley Scott", new DateTime(1979,06,22), "After investigating an S.O.S. signal on a near-by world, the crew of an industrial spacecraft must fight for survival when a highly aggressive bioform is born in the ship and begins hunting them one by one.", new[] { horror, sciFi }), 
                new Movie("tt0027977", "Modern Times", 8.6m, "Charles Chaplin", new DateTime(1936,02,25), "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.", new[] { comedy, drama }), 
                new Movie("tt0053125", "North by Northwest", 8.5m, "Alfred Hitchcock", new DateTime(1959,09,26), "A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.", new[] { action, adventure, crime, mystery, thriller }), 
                new Movie("tt0088763", "Back to the Future", 8.5m, "Robert Zemeckis", new DateTime(1985,07,03), "A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown, and must make sure his high-school-age parents unite in order to save his own existence.", new[] { adventure, comedy, sciFi }), 
                new Movie("tt0033467", "Citizen Kane", 8.5m, "Orson Welles", new DateTime(1941,09,05), "Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance.", new[] { drama, mystery }), 
                new Movie("tt0081505", "The Shining", 8.5m, "Stanley Kubrick", new DateTime(1980,05,23), "A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.", new[] { horror, mystery }), 
                new Movie("tt0253474", "The Pianist", 8.5m, "Roman Polanski", new DateTime(2003,03,28), "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.", new[] { biography, drama, history, war }), 
                new Movie("tt0407887", "The Departed", 8.5m, "Martin Scorsese", new DateTime(2006,10,06), "An undercover state cop who infiltrated a Mafia clan and a mole in the police force working for the same mob race to track down and identify each other before being exposed to the enemy, after both sides realize their outfit has a rat.", new[] { crime, drama, thriller }), 
                new Movie("tt0022100", "M", 8.5m, "Fritz Lang", new DateTime(1931,08,31), "When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.", new[] { crime, drama, thriller }), 
                new Movie("tt0052357", "Vertigo", 8.5m, "Alfred Hitchcock", new DateTime(1958,07,21), "A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's much-younger wife, all the while becoming dangerously obsessed with her.", new[] { mystery, romance, thriller }), 
                new Movie("tt0050825", "Paths of Glory", 8.5m, "Stanley Kubrick", new DateTime(1957,10,25), "When soldiers in World War I refuse to continue with an impossible attack, their superior officers decide to make an example of them.", new[] { drama, war }), 
                new Movie("tt1853728", "Django Unchained", 8.5m, "Quentin Tarantino", new DateTime(2013,05,12), "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", new[] { adventure, drama, western }), 
                new Movie("tt1345836", "The Dark Knight Rises", 8.6m, "Christopher Nolan", new DateTime(2012,08,28), "Eight years on, a new evil rises from where the Batman and Commissioner Gordon tried to bury it, causing the Batman to resurface and fight to protect Gotham City... the very city which brands him an enemy.", new[] { action, crime, thriller }), 
                new Movie("tt0075314", "Taxi Driver", 8.5m, "Martin Scorsese", new DateTime(1976,02,08), "A mentally unstable Viet Nam war veteran works as a night-time taxi driver in New York City where the perceived decadence and sleaze feeds his urge for violent action, attempting to save a preadolescent prostitute in the process.", new[] { crime, drama }), 
                new Movie("tt0169547", "American Beauty", 8.5m, "Sam Mendes", new DateTime(1999,10,01), "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation for his daughter's attractive friend.", new[] { drama }), 
                new Movie("tt0090605", "Aliens", 8.5m, "James Cameron", new DateTime(1986,07,18), "The planet from  has been colonized, but contact is lost. This time, the rescue team has impressive firepower, but will it be enough?", new[] { action, adventure, sciFi, thriller }), 
                new Movie("tt0036775", "Double Indemnity", 8.5m, "Billy Wilder", new DateTime(1944,04,24), "An insurance rep lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator's suspicions.", new[] { crime, drama, filmNoir, thriller }), 
                new Movie("tt0120689", "The Green Mile", 8.5m, "Frank Darabont", new DateTime(1999,12,10), "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.", new[] { crime, drama, fantasy, mystery }), 
                new Movie("tt0172495", "Gladiator", 8.5m, "Ridley Scott", new DateTime(2000,05,05), "When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.", new[] { action, adventure, drama }), 
                new Movie("tt0910970", "WALL·E", 8.5m, "Andrew Stanton", new DateTime(2008,06,27), "In the distant future, a small waste collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.", new[] { animation, adventure, family, romance, sciFi }), 
                new Movie("tt0435761", "Toy Story 3", 8.5m, "Lee Unkrich", new DateTime(2010,06,16), "The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.", new[] { animation, adventure, comedy, family, fantasy }), 
                new Movie("tt0032553", "The Great Dictator", 8.5m, "Charles Chaplin", new DateTime(1941,03,07), "Dictator Adenoid Hynkel has a doppelganger, a poor but kind Jewish barber living in the slums, who one day is mistaken for Hynkel.", new[] { comedy, drama, war }), 
                new Movie("tt0066921", "A Clockwork Orange", 8.4m, "Stanley Kubrick", new DateTime(1972,02,02), "In future Britain, charismatic delinquent Alex DeLarge is jailed and volunteers for an experimental aversion therapy developed by the government in an effort to solve society's crime problem... but not all goes to plan.", new[] { crime, drama, sciFi }), 
                new Movie("tt0482571", "The Prestige", 8.4m, "Christopher Nolan", new DateTime(2006,10,20), "The rivalry between two magicians becomes more exacerbated by their attempt to perform the ultimate illusion.", new[] { drama, mystery, thriller }), 
                new Movie("tt0056172", "Lawrence of Arabia", 8.4m, "David Lean", new DateTime(1963,01,30), "A flamboyant and controversial British military figure and his conflicted loyalties during his World War I service in Arabia.", new[] { adventure, biography, drama, history, war }), 
                new Movie("tt0056592", "To Kill a Mockingbird", 8.4m, "Robert Mulligan", new DateTime(1963,03,16), "Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his kids against prejudice.", new[] { crime, drama, mystery }), 
                new Movie("tt0105236", "Reservoir Dogs", 8.4m, "Quentin Tarantino", new DateTime(1992,10,23), "After a simple jewelery heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.", new[] { crime, thriller }), 
                new Movie("tt0082096", "Das Boot", 8.4m, "Wolfgang Petersen", new DateTime(1982,02,10), "The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.", new[] { action, adventure, drama, history, war }), 
                new Movie("tt0110357", "The Lion King", 8.4m, "Roger Allers", new DateTime(1995,07,15), "Tricked into thinking he killed his father, a guilt ridden lion cub flees into exile and abandons his identity as the future King.", new[] { animation, adventure, drama, family, musical }), 
                new Movie("tt0040897", "The Treasure of the Sierra Madre", 8.4m, "John Huston", new DateTime(1948,01,24), "Fred Dobbs and Bob Curtin, two Americans searching for work in Mexico, convince an old prospector to help them mine for gold in the Sierra Madre Mountains.", new[] { action, adventure, drama, western }), 
                new Movie("tt0041959", "The Third Man", 8.4m, "Carol Reed", new DateTime(1949,08,31), "Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, black-market opportunist Harry Lime.", new[] { filmNoir, mystery, thriller }), 
                new Movie("tt0086190", "Star Wars: Episode VI - Return of the Jedi", 8.4m, "Richard Marquand", new DateTime(1983,05,25), "After rescuing Han Solo from the palace of Jabba the Hutt, the Rebels attempt to destroy the Second Death Star, while Luke Skywalker tries to bring his father back to the Light Side of the Force.", new[] { action, adventure, fantasy, sciFi }), 
                new Movie("tt0180093", "Requiem for a Dream", 8.4m, "Darren Aronofsky", new DateTime(2000,10,27), "The drug-induced utopias of four Coney Island individuals are shattered when their addictions become stronger.", new[] { drama }), 
                new Movie("tt0087843", "Once Upon a Time in America", 8.4m, "Sergio Leone", new DateTime(1984,09,28), "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.", new[] { crime, drama }), 
                new Movie("tt0338013", "Eternal Sunshine of the Spotless Mind", 8.4m, "Michel Gondry", new DateTime(2004,03,19), "A couple undergo a procedure to erase each other from their memories when their relationship turns sour, but it is only through the process of loss that they discover what they had to begin with.", new[] { drama, romance, sciFi }), 
                new Movie("tt0093058", "Full Metal Jacket", 8.4m, "Stanley Kubrick", new DateTime(1987,06,26), "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow Marine recruits from their brutal boot camp training to the bloody street fighting set in 1968 in Hue, Vietnam.", new[] { drama, war }), 
                new Movie("tt0112573", "Braveheart", 8.4m, "Mel Gibson", new DateTime(1995,05,24), "When his secret bride is executed for assaulting an English soldier whom tried to rape her, a commoner begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron-fist.", new[] { action, biography, drama, history, war }), 
                new Movie("tt0364569", "Oldeuboi", 8.4m, "Chan-wook Park", new DateTime(2003,11,21), "After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.", new[] { drama, mystery, thriller }), 
                new Movie("tt0119488", "L.A. Confidential", 8.4m, "Curtis Hanson", new DateTime(1997,09,19), "As corruption grows in 1950s LA, three policemen - the straight-laced, the brutal, and the sleazy - investigate a series of murders with their own brand of justice.", new[] { crime, drama, mystery, thriller }), 
                new Movie("tt0045152", "Singin' in the Rain", 8.4m, "Stanley Donen", new DateTime(1981,05,15), "A silent film production company and cast make a difficult transition to sound.", new[] { comedy, musical, romance }), 
                new Movie("tt0071315", "Chinatown", 8.4m, "Roman Polanski", new DateTime(1974,06,20), "A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption and murder.", new[] { crime, drama, mystery, thriller }), 
                new Movie("tt0071853", "Monty Python and the Holy Grail", 8.4m, "Terry Gilliam", new DateTime(1975,05,25), "King Arthur and his knights embark on a low-budget search for the Grail, encountering many very silly obstacles.", new[] { adventure, comedy, fantasy }), 
                new Movie("tt0053291", "Some Like It Hot", 8.4m, "Billy Wilder", new DateTime(1959,03,29), "When two musicians witness a mob hit, they flee the state in an all female band disguised as women, but further complications set in.", new[] { comedy }), 
                new Movie("tt0017136", "Metropolis", 8.4m, "Fritz Lang", new DateTime(1927,03,13), "In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.", new[] { drama, sciFi }), 
                new Movie("tt0086879", "Amadeus", 8.4m, "Milos Forman", new DateTime(1984,09,19), "The incredible story of Wolfgang Amadeus Mozart, told by his peer and secret rival Antonio Salieri - now confined to an insane asylum.", new[] { biography, drama, music }), 
                new Movie("tt0062622", "2001: A Space Odyssey", 8.3m, "Stanley Kubrick", new DateTime(1968,04,11), "Humanity finds a mysterious, obviously artificial, object buried beneath the Lunar surface and, with the intelligent computer H.A.L. 9000, sets off on a quest.", new[] { adventure, mystery, sciFi }), 
                new Movie("tt0042192", "All About Eve", 8.4m, "Joseph L. Mankiewicz", new DateTime(1951,01,15), "An ingenue insinuates herself in to the company of an established but aging stage actress and her circle of theater friends.", new[] { drama }), 
                new Movie("tt0070735", "The Sting", 8.3m, "George Roy Hill", new DateTime(1974,01,10), "In 1930s Chicago, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker.", new[] { comedy, crime, drama }), 
                new Movie("tt0053604", "The Apartment", 8.4m, "Billy Wilder", new DateTime(1960,09,16), "A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.", new[] { comedy, drama, romance }), 
                new Movie("tt0105695", "Unforgiven", 8.3m, "Clint Eastwood", new DateTime(1992,08,07), "Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.", new[] { western }), 
                new Movie("tt0097576", "Indiana Jones and the Last Crusade", 8.3m, "Steven Spielberg", new DateTime(1989,05,24), "When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana Jones must follow in his father's footsteps and stop the Nazis.", new[] { action, adventure }), 
            };

            return movies;
        }
    }
}